# Site settings
title: Damian Wiliński
description: 'IT and Architecture student'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Damian Wiliński'
  email: damian.wilinski@gmail.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  damwilin
  linkedin_username:  damian-wiliński-90a429111

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
