# Site settings
title: Damian Wiliński
description: 'IT and Architecture student'
url: 'damianwilinski.pl'
baseurl: '/'
google_analytics: 'UA-38650312-2'
disqus_shortname: 'wili'

author:
  name: 'Damian Wiliński'
  email: damian.wilinski@gmail.com
  github_username:  damwilin
  linkedin_username:  damian-wiliński-90a429111
  behance_username: damianwilinski
  flickr_username: damian.wilinski

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
